version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: task-manager-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=task-manager
    restart: unless-stopped
    networks:
      - app-network

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: task-manager-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: task-manager-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/task-manager
      - JWT_SECRET=task_manager_secret_key_change_in_production
      - JWT_EXPIRES_IN=7d
    depends_on:
      - mongodb
      - mongo-express
    restart: unless-stopped
    networks:
      - app-network

  # Frontend React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: task-manager-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 